trigger: none
pr: 
  branches:
      include: # branch names which will trigger a build	
      - dev	
      - master
  paths:
    exclude: # file paths which must match to trigger a build	
      - bluegreen/deploy.yaml
jobs: # A job is a collection of steps to be run by an agent 	
- job: BuildGolangDeps
  timeoutInMinutes: 90  # how long to run the job before automatically cancelling	
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    displayName: 'Build and Push Golang dependencies'
    inputs:
      containerRegistry: $(registry) # input registry name	
      repository: presidio-golang-deps # name of image to build	
      Dockerfile: Dockerfile.golang.deps # dockerfile path	
      tags: | # image tags	
        $(Build.BuildId)	
  - task: Docker@2
    displayName: 'Build and Push Python dependencies'
    inputs:
      containerRegistry: $(registry) # input registry name	
      repository: 'presidio-python-deps'
      Dockerfile: Dockerfile.python.deps # dockerfile path
      tags: | # image tags	
        $(Build.BuildId)	

