apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $NAME-$RELEASE_ID
spec:
  replicas: $REPLICA_COUNT
  template:
    metadata:
      labels:
        name: $NAME
        release: "$RELEASE_ID"
    spec:
      containers: 
        - name: $NAME
          image: $IMAGE_NAME
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: $NAME$RELEASE_ID-test
  labels: 
    release: "$RELEASE_ID"
    name: $NAME
    serviceName: $NAME$RELEASE_ID
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name : $NAME
    release: "$RELEASE_ID"