apiVersion: v1
kind: Service
metadata: 
  name: $NAME
  labels: 
    release: "$RELEASE_ID"
    name: $NAME
    serviceName: $NAME$RELEASE_ID
    state: $STATE
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name : $NAME
    release: "$RELEASE_ID"