apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    tag: nginx
    release: "$RELEASE_ID"
    state: green
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx$RELEASE_ID
          servicePort: 80